# Generated by Django 3.2.7 on 2021-09-09 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('show_checked', models.BooleanField(default=True, verbose_name='Показывать выполненные')),
            ],
            options={
                'verbose_name': 'список дел',
                'verbose_name_plural': 'списки дел',
            },
        ),
        migrations.CreateModel(
            name='TaskTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('is_checked', models.BooleanField(default=False)),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todosite.todolist', verbose_name='Название списка')),
            ],
            options={
                'verbose_name': 'задача списка дел',
                'verbose_name_plural': 'задачи списков дел',
            },
        ),
    ]
