# Generated by Django 3.2.7 on 2021-09-10 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todosite', '0002_auto_20210910_0932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskTodo',
            new_name='Task',
        ),
    ]
